### PR TITLE
[1.8] Backport PHP 8.4 compat fixes

### PR DESCRIPTION
**Pull request by jtojnar**

### CODE REVIEW

**Comment by jrfnl** [comment]
This will also need the fixes from PRs #880 and #881.

**Review by Alkarex — APPROVED** [review]

**Review by Art4 — APPROVED** [review]

**Comment by jtojnar** [comment]
Cherry picked the latter, the former is not relevant as there are no typehints in this branch.

**Comment by jtojnar** [comment]
@Art4 If there are no other critical changes to backport, I propose merging this and then tagging 1.8.1.

We can make 1.8.2 with the other fixes like  #883 later.

**Comment by Art4** [comment]
@jtojnar I'm fine with releasing 1.8.1. Will you create the PR?

**Comment by jtojnar** [comment]
Okay, opened #886 and moved the chnagelog + constant there.

**Comment by jrfnl** [comment]
> Cherry picked the latter, the former is not relevant as there are no typehints in this branch.

Sorry to correct you, but you're wrong. The IRI class may not have type declarations in 1.8, the `Sanitize` class does and the PHP 8.4 fix for that **will** need a backport.

https://github.com/simplepie/simplepie/blob/c5d51872adc226b28281272df67de587c5511af5/src/Sanitize.php#L135

```diff
-    public function pass_cache_data($enable_cache = true, $cache_location = './cache', $cache_name_function = 'md5', $cache_class = 'SimplePie\Cache', DataCache $cache = null)
+    public function pass_cache_data($enable_cache = true, $cache_location = './cache', $cache_name_function = 'md5', $cache_class = 'SimplePie\Cache', ?DataCache $cache = null)
```

**Comment by jtojnar** [comment]
Oops, I did not scroll far enough in merge conflict resolution.

Opened https://github.com/simplepie/simplepie/pull/888

**Pull request merged**
