### PR TITLE
"Empty needle"-silencer

### PR DESCRIPTION
**Pull request by JanPetterMG**
Don't add photo if URL is empty
Fix for #529

### CODE REVIEW

**Comment by mblaney** [comment]
thanks! (btw, I went looking through my own code and found I never add brackets to clarify operator precedence, so wasn't the best suggestion...)

**Comment by JanPetterMG** [comment]
Yeah, noticed that, I didn't find any myself either (at least not in this file)...

Btw, do you mind pushing those mf2 fixes you talked about? Thanks! https://github.com/simplepie/simplepie/issues/529#issuecomment-316244312

**Comment by mblaney** [comment]
@JanPetterMG mf2 fixes in #533

**Comment by JanPetterMG** [comment]
@mblaney Great! :tada:

**Pull request merged**
