### PR TITLE
Update version to 1.4.

### PR DESCRIPTION
**Pull request by mblaney**

### CODE REVIEW

**Comment by mblaney** [comment]
SimplePie 1.4 is available! Thanks to everyone who has contributed since the last release.

**Comment by skyzyx** [comment]
Wooooooo!!!

**Comment by JanPetterMG** [comment]
Why isn't the phpDoc fixes in PR #440 merged? You really want to release 1.4.1 just for them?

And what about the recent discovered problems? #441 affecting multiple feeds at multiple pages, wouldn't it be fair to wait a few more days?

I can tell a fix is needed, no matter who's problem it is, an error is generated, due to badly written php code. Either we should check the input (_easy fix_), or fix the problem (_may be complicated, I don't know_)

I'll wait for 1.4.1, (or rolling back to ``1.3.1``) because there is no difference between the buggy ``1.4-beta`` and now released ``1.4``...

**Comment by mblaney** [comment]
Hi @JanPetterMG, you did say you were going to keep adding to #440, so thought it best to hold off until you're done. Not that I really agree with the change, but if it works better for you that's fine.

#441 just generates a notice, but PR happily accepted.

**Comment by mblaney** [comment]
@skyzyx do you know who has access to the simplepie.org website? Would be great to make some updates there too.

**Comment by skyzyx** [comment]
Last I heard (≈5 years ago), @rmccue was working with someone on the WordPress team to take over hosting the site. He would know better than I would what happened after that.

**Comment by rmccue** [comment]
@mblaney Sorry for the late update here; forgot to comment when I read it! Drop me an email at the address [on my site](https://rmccue.io/) under Contact and I can get you set up with everything :)

Yay for updates!

**Pull request merged**
