### PR TITLE
Release 1.8.0

### PR DESCRIPTION
**Pull request by Art4**
In this PR we can prepare everything for the release of SimplePie 1.8.0

Check list:

- [x] bump version in constant `SimplePie\SimplePie::VERSION`.
- [x] Add entries for all changes in `CHANGLOG.md`.
- [x] Add missing authors and issues in `CHANGLOG.md` if necessary.
- [x] Fix code style by running `bin/php-cs-fixer fix`.

### CODE REVIEW

**Comment by Art4** [comment]
> That looks good. I still want to try using the new cache in [selfoss](https://github.com/fossar/selfoss) before the release to check the ergonomics in practice.

That would be great. 👍 I am looking forward to your feedback.

**Comment by jtojnar** [comment]
I tried using the PSR-16 cache with `symfony/cache` in https://github.com/fossar/selfoss/pull/1394 and it works okay.

**Comment by Art4** [comment]
Hey @mblaney, after the decision about #766 everything should be ready for release 1.8.0. What do you think about picking a date for the release? Than I could finalize this PR and can continue working on the refactoring.

**Comment by mblaney** [comment]
ok great @Art4 maybe next Friday the 20th?

**Comment by Art4** [comment]
> maybe next Friday the 20th?

@mblaney Ok, I've updated the PR and added the date in the `CHANGELOG.md`. If there will be more merges in the meantime I will update the PR.

**Comment by mblaney** [comment]
@Art4 I've merged a few PRs if you want to update the change log, sorry for the short notice.

**Comment by Art4** [comment]
I will update the PR in the next hours.

**Comment by Art4** [comment]
@mblaney The CHANGELOG.md is up to date. This PR is ready for merge and 1.8.0 ready for release.

**Pull request merged**
