### PR TITLE
New Release 1.6.0?

### PR DESCRIPTION
**Pull request by Art4**
May I ask, if there could be new release in the near future? I would like to use the namespaced classes (#711) in production.  

For this case I updated the CHANGELOG.md and bump the version number to 1.6.0 with this PR.

### CODE REVIEW

**Comment by mblaney** [comment]
hey @Art4 any idea why there's composer errors with the last update?

**Comment by Art4** [comment]
My first guess: newest composer requires PHP 7.2. To use it with PHP <7.2 we have to use composer 2.2.x, see https://getcomposer.org/download/

> Manual Download
> 
> If you prefer to download the phar manually, here are the available versions:
> 
> [Latest Stable](https://getcomposer.org/download/latest-stable/composer.phar) ([sha256](https://getcomposer.org/download/latest-stable/composer.phar.sha256) / [sha256sum](https://getcomposer.org/download/latest-stable/composer.phar.sha256sum) / [asc](https://getcomposer.org/download/latest-stable/composer.phar.asc)) **for PHP 7.2+ users**
> [...]
> [Latest 2.2.x LTS](https://getcomposer.org/download/latest-2.2.x/composer.phar) ([sha256](https://getcomposer.org/download/latest-2.2.x/composer.phar.sha256) / [sha256sum](https://getcomposer.org/download/latest-2.2.x/composer.phar.sha256sum) / [asc](https://getcomposer.org/download/latest-2.2.x/composer.phar.asc)) **for PHP 5.3 to 7.1 users**

**Comment by Art4** [comment]
I've specified the composer version to 2.2 LTS on PHP <= 7.1 and now all checks are working again.

**Comment by mblaney** [comment]
great, thanks @Art4!

**Pull request merged**
