### PR TITLE
Create tests for PSR-4 classes, refactor oldtests

### PR DESCRIPTION
**Pull request by Art4**
The goal of this PR is to copy and revise as many tests as possible to test against the PSR-4 (namespaced) classes. The old tests for PSR-0 (without namespaces) will remain untouched if possible to ensure BC.

Update: After working my way through the `oldtests` folder, I decided to migrate these very old tests directly after all, to minimize future workload.

**This PR relies on merging #722** and still needs some work.

This PR is a subtask of #731.

### CODE REVIEW

**Comment by Art4** [comment]
This PR is ready for review, but still relies on merging of #722.

**Comment by Art4** [comment]
I resolved all merge conflicts after merge of #722.

**Comment by mblaney** [comment]
In general I would say the copyright year shouldn't change when it's the only modification to a file, but all good for now.

**Comment by Art4** [comment]
Thank you. I agree with you in principle about the year but it was a follow up change from #727 to keep all headers consistent.

**Pull request merged**
