### PR TITLE
Improved error message

### PR DESCRIPTION
**Pull request by SteffenPegenau**
If there is an encoding error, it would be nice to know on which feed

### CODE REVIEW

**Comment by samwilson** [comment]
+1 for this! It's super-annoying when parsing a hundred feeds to have some error somwhere and not know which feed to investigate. :)

**Comment by danpoltawski** [comment]
+1 Ping.

**Comment by mblaney** [comment]
fixed by 061d630

**Comment by samwilson** [comment]
Thanks @mblaney :)

**Pull request closed without merging**
