### PR TITLE
Upload compiled file as asset + tests

### LINKED ISSUE #544: Compiled form / build script absent from newer releases
Simplepie 1.3.x used to provide the "compiled" monolithic version directly as a download on the website, which was quite convenient.

I saw this in README.markdown in the 1.5 tarball today:

> If you'd like a single monolithic file, you can run `php build/compile.php` to generate `SimplePie.compiled.php`.

...except the build dir doesn't exist in the release tarballs, so I thought it didn't exist at all, until I found it in git master. So I would think either the compiled form should also be available as a download on the website, or the build dir should be present in the released tarballs, or the README.markdown file should explain where to get it exactly.

### PR DESCRIPTION
**Pull request by Art4**
As I continued to work on #722, I noticed that there are no tests for the output of `build/compile.php`. So I created a new workflow that runs all tests also with the code in the single file. This way we make sure that the single file always works as well. This is especially important when switching to namespaced classes.

Additionally I had the idea, that we can offer the `SimplePie.compiled.php` directly as an asset for download at a release. I have created a separate Github workflow for this purpose.

This PR could also potentially fix #544.

### CODE REVIEW

**Comment by Art4** [comment]
I've integrated the tests for the compiled file into the existing ci workflow.

**Comment by Art4** [comment]
Any thoughts or questions? Is there anything I could improve? I would like to continue working on #722, but would need a decision if this PR is accepted.

**Comment by mblaney** [comment]
looks good @Art4 thanks and sorry it took me a while to get to it

**Comment by Art4** [comment]
You're welcome. No problem, I'm patient. 😊

**Pull request merged**
