### PR TITLE
The "version" should never be declaired like that

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by GaryJones** [comment]
A little more context would be appreciated here I think.

**Comment by GrahamCampbell** [comment]
Packagist uses git tags to work out the version. You should never specify it like that in the composer.json as it just conflicts with git creating a mess where every new commit redefines the what the release is so every commit you push is now that release.

**Comment by GrahamCampbell** [comment]
This leads to a massive mess with composer's caching because it's now undefined what users actually end up with because composer was designed under the assumption releases aren't retagged.

**Comment by GrahamCampbell** [comment]
Ping.

**Comment by rmccue** [comment]
Thanks! :)

**Pull request merged**
