### PR TITLE
Raise PHPStan to level 6

### PR DESCRIPTION
**Pull request by jtojnar**

### CODE REVIEW

**Comment by mblaney** [comment]
sorry I've been away, it this ok to merge or do we need to look at other pr's first?

**Comment by jtojnar** [comment]
@mblaney Looks like new versions of dev dependencies broke the CI.  #841 should be merged first.

**Comment by jtojnar** [comment]
@mblaney I have fixed the issues.

**Comment by mblaney** [comment]
thanks @jtojnar can someone confirm this won't affect #777? otherwise will wait to hear about which should be merged first

**Comment by Art4** [comment]
> can someone confirm this won't affect #777? otherwise will wait to hear about which should be merged first

At a first glance the changes should not collied with #777. But even if they are, the conflicts should be very easy to resolve

**Pull request merged**
